# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/odrevet/builds/gjitenkai

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/odrevet/builds/gjitenkai

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/odrevet/builds/gjitenkai/CMakeFiles /home/odrevet/builds/gjitenkai/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/odrevet/builds/gjitenkai/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin/gjitenkai

# Build rule for target.
bin/gjitenkai: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/gjitenkai
.PHONY : bin/gjitenkai

# fast build rule for target.
bin/gjitenkai/fast:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/build
.PHONY : bin/gjitenkai/fast

#=============================================================================
# Target rules for targets named bin/kanjidic

# Build rule for target.
bin/kanjidic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/kanjidic
.PHONY : bin/kanjidic

# fast build rule for target.
bin/kanjidic/fast:
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/build
.PHONY : bin/kanjidic/fast

#=============================================================================
# Target rules for targets named bin/worddic

# Build rule for target.
bin/worddic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/worddic
.PHONY : bin/worddic

# fast build rule for target.
bin/worddic/fast:
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/build
.PHONY : bin/worddic/fast

src/common/callbacks.o: src/common/callbacks.c.o
.PHONY : src/common/callbacks.o

# target to build an object file
src/common/callbacks.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/common/callbacks.c.o
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/common/callbacks.c.o
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/common/callbacks.c.o
.PHONY : src/common/callbacks.c.o

src/common/callbacks.i: src/common/callbacks.c.i
.PHONY : src/common/callbacks.i

# target to preprocess a source file
src/common/callbacks.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/common/callbacks.c.i
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/common/callbacks.c.i
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/common/callbacks.c.i
.PHONY : src/common/callbacks.c.i

src/common/callbacks.s: src/common/callbacks.c.s
.PHONY : src/common/callbacks.s

# target to generate assembly for a file
src/common/callbacks.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/common/callbacks.c.s
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/common/callbacks.c.s
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/common/callbacks.c.s
.PHONY : src/common/callbacks.c.s

src/common/conf.o: src/common/conf.c.o
.PHONY : src/common/conf.o

# target to build an object file
src/common/conf.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/common/conf.c.o
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/common/conf.c.o
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/common/conf.c.o
.PHONY : src/common/conf.c.o

src/common/conf.i: src/common/conf.c.i
.PHONY : src/common/conf.i

# target to preprocess a source file
src/common/conf.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/common/conf.c.i
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/common/conf.c.i
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/common/conf.c.i
.PHONY : src/common/conf.c.i

src/common/conf.s: src/common/conf.c.s
.PHONY : src/common/conf.s

# target to generate assembly for a file
src/common/conf.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/common/conf.c.s
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/common/conf.c.s
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/common/conf.c.s
.PHONY : src/common/conf.c.s

src/common/dicfile.o: src/common/dicfile.c.o
.PHONY : src/common/dicfile.o

# target to build an object file
src/common/dicfile.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/common/dicfile.c.o
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/common/dicfile.c.o
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/common/dicfile.c.o
.PHONY : src/common/dicfile.c.o

src/common/dicfile.i: src/common/dicfile.c.i
.PHONY : src/common/dicfile.i

# target to preprocess a source file
src/common/dicfile.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/common/dicfile.c.i
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/common/dicfile.c.i
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/common/dicfile.c.i
.PHONY : src/common/dicfile.c.i

src/common/dicfile.s: src/common/dicfile.c.s
.PHONY : src/common/dicfile.s

# target to generate assembly for a file
src/common/dicfile.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/common/dicfile.c.s
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/common/dicfile.c.s
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/common/dicfile.c.s
.PHONY : src/common/dicfile.c.s

src/common/dicutil.o: src/common/dicutil.c.o
.PHONY : src/common/dicutil.o

# target to build an object file
src/common/dicutil.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/common/dicutil.c.o
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/common/dicutil.c.o
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/common/dicutil.c.o
.PHONY : src/common/dicutil.c.o

src/common/dicutil.i: src/common/dicutil.c.i
.PHONY : src/common/dicutil.i

# target to preprocess a source file
src/common/dicutil.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/common/dicutil.c.i
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/common/dicutil.c.i
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/common/dicutil.c.i
.PHONY : src/common/dicutil.c.i

src/common/dicutil.s: src/common/dicutil.c.s
.PHONY : src/common/dicutil.s

# target to generate assembly for a file
src/common/dicutil.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/common/dicutil.c.s
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/common/dicutil.c.s
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/common/dicutil.c.s
.PHONY : src/common/dicutil.c.s

src/common/error.o: src/common/error.c.o
.PHONY : src/common/error.o

# target to build an object file
src/common/error.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/common/error.c.o
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/common/error.c.o
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/common/error.c.o
.PHONY : src/common/error.c.o

src/common/error.i: src/common/error.c.i
.PHONY : src/common/error.i

# target to preprocess a source file
src/common/error.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/common/error.c.i
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/common/error.c.i
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/common/error.c.i
.PHONY : src/common/error.c.i

src/common/error.s: src/common/error.c.s
.PHONY : src/common/error.s

# target to generate assembly for a file
src/common/error.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/common/error.c.s
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/common/error.c.s
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/common/error.c.s
.PHONY : src/common/error.c.s

src/gjitenkai/callbacks.o: src/gjitenkai/callbacks.c.o
.PHONY : src/gjitenkai/callbacks.o

# target to build an object file
src/gjitenkai/callbacks.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/gjitenkai/callbacks.c.o
.PHONY : src/gjitenkai/callbacks.c.o

src/gjitenkai/callbacks.i: src/gjitenkai/callbacks.c.i
.PHONY : src/gjitenkai/callbacks.i

# target to preprocess a source file
src/gjitenkai/callbacks.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/gjitenkai/callbacks.c.i
.PHONY : src/gjitenkai/callbacks.c.i

src/gjitenkai/callbacks.s: src/gjitenkai/callbacks.c.s
.PHONY : src/gjitenkai/callbacks.s

# target to generate assembly for a file
src/gjitenkai/callbacks.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/gjitenkai/callbacks.c.s
.PHONY : src/gjitenkai/callbacks.c.s

src/gjitenkai/gjitenkai.o: src/gjitenkai/gjitenkai.c.o
.PHONY : src/gjitenkai/gjitenkai.o

# target to build an object file
src/gjitenkai/gjitenkai.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/gjitenkai/gjitenkai.c.o
.PHONY : src/gjitenkai/gjitenkai.c.o

src/gjitenkai/gjitenkai.i: src/gjitenkai/gjitenkai.c.i
.PHONY : src/gjitenkai/gjitenkai.i

# target to preprocess a source file
src/gjitenkai/gjitenkai.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/gjitenkai/gjitenkai.c.i
.PHONY : src/gjitenkai/gjitenkai.c.i

src/gjitenkai/gjitenkai.s: src/gjitenkai/gjitenkai.c.s
.PHONY : src/gjitenkai/gjitenkai.s

# target to generate assembly for a file
src/gjitenkai/gjitenkai.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/gjitenkai/gjitenkai.c.s
.PHONY : src/gjitenkai/gjitenkai.c.s

src/gjitenkai/main.o: src/gjitenkai/main.c.o
.PHONY : src/gjitenkai/main.o

# target to build an object file
src/gjitenkai/main.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/gjitenkai/main.c.o
.PHONY : src/gjitenkai/main.c.o

src/gjitenkai/main.i: src/gjitenkai/main.c.i
.PHONY : src/gjitenkai/main.i

# target to preprocess a source file
src/gjitenkai/main.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/gjitenkai/main.c.i
.PHONY : src/gjitenkai/main.c.i

src/gjitenkai/main.s: src/gjitenkai/main.c.s
.PHONY : src/gjitenkai/main.s

# target to generate assembly for a file
src/gjitenkai/main.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/gjitenkai/main.c.s
.PHONY : src/gjitenkai/main.c.s

src/kanjidic/callbacks.o: src/kanjidic/callbacks.c.o
.PHONY : src/kanjidic/callbacks.o

# target to build an object file
src/kanjidic/callbacks.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/callbacks.c.o
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/callbacks.c.o
.PHONY : src/kanjidic/callbacks.c.o

src/kanjidic/callbacks.i: src/kanjidic/callbacks.c.i
.PHONY : src/kanjidic/callbacks.i

# target to preprocess a source file
src/kanjidic/callbacks.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/callbacks.c.i
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/callbacks.c.i
.PHONY : src/kanjidic/callbacks.c.i

src/kanjidic/callbacks.s: src/kanjidic/callbacks.c.s
.PHONY : src/kanjidic/callbacks.s

# target to generate assembly for a file
src/kanjidic/callbacks.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/callbacks.c.s
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/callbacks.c.s
.PHONY : src/kanjidic/callbacks.c.s

src/kanjidic/kanji_item.o: src/kanjidic/kanji_item.c.o
.PHONY : src/kanjidic/kanji_item.o

# target to build an object file
src/kanjidic/kanji_item.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/kanji_item.c.o
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/kanji_item.c.o
.PHONY : src/kanjidic/kanji_item.c.o

src/kanjidic/kanji_item.i: src/kanjidic/kanji_item.c.i
.PHONY : src/kanjidic/kanji_item.i

# target to preprocess a source file
src/kanjidic/kanji_item.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/kanji_item.c.i
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/kanji_item.c.i
.PHONY : src/kanjidic/kanji_item.c.i

src/kanjidic/kanji_item.s: src/kanjidic/kanji_item.c.s
.PHONY : src/kanjidic/kanji_item.s

# target to generate assembly for a file
src/kanjidic/kanji_item.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/kanji_item.c.s
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/kanji_item.c.s
.PHONY : src/kanjidic/kanji_item.c.s

src/kanjidic/kanjidic.o: src/kanjidic/kanjidic.c.o
.PHONY : src/kanjidic/kanjidic.o

# target to build an object file
src/kanjidic/kanjidic.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/kanjidic.c.o
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/kanjidic.c.o
.PHONY : src/kanjidic/kanjidic.c.o

src/kanjidic/kanjidic.i: src/kanjidic/kanjidic.c.i
.PHONY : src/kanjidic/kanjidic.i

# target to preprocess a source file
src/kanjidic/kanjidic.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/kanjidic.c.i
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/kanjidic.c.i
.PHONY : src/kanjidic/kanjidic.c.i

src/kanjidic/kanjidic.s: src/kanjidic/kanjidic.c.s
.PHONY : src/kanjidic/kanjidic.s

# target to generate assembly for a file
src/kanjidic/kanjidic.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/kanjidic.c.s
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/kanjidic.c.s
.PHONY : src/kanjidic/kanjidic.c.s

src/kanjidic/kanjifile.o: src/kanjidic/kanjifile.c.o
.PHONY : src/kanjidic/kanjifile.o

# target to build an object file
src/kanjidic/kanjifile.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/kanjifile.c.o
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/kanjifile.c.o
.PHONY : src/kanjidic/kanjifile.c.o

src/kanjidic/kanjifile.i: src/kanjidic/kanjifile.c.i
.PHONY : src/kanjidic/kanjifile.i

# target to preprocess a source file
src/kanjidic/kanjifile.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/kanjifile.c.i
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/kanjifile.c.i
.PHONY : src/kanjidic/kanjifile.c.i

src/kanjidic/kanjifile.s: src/kanjidic/kanjifile.c.s
.PHONY : src/kanjidic/kanjifile.s

# target to generate assembly for a file
src/kanjidic/kanjifile.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/kanjifile.c.s
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/kanjifile.c.s
.PHONY : src/kanjidic/kanjifile.c.s

src/kanjidic/kanjiutils.o: src/kanjidic/kanjiutils.c.o
.PHONY : src/kanjidic/kanjiutils.o

# target to build an object file
src/kanjidic/kanjiutils.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/kanjiutils.c.o
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/kanjiutils.c.o
.PHONY : src/kanjidic/kanjiutils.c.o

src/kanjidic/kanjiutils.i: src/kanjidic/kanjiutils.c.i
.PHONY : src/kanjidic/kanjiutils.i

# target to preprocess a source file
src/kanjidic/kanjiutils.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/kanjiutils.c.i
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/kanjiutils.c.i
.PHONY : src/kanjidic/kanjiutils.c.i

src/kanjidic/kanjiutils.s: src/kanjidic/kanjiutils.c.s
.PHONY : src/kanjidic/kanjiutils.s

# target to generate assembly for a file
src/kanjidic/kanjiutils.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/kanjiutils.c.s
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/kanjiutils.c.s
.PHONY : src/kanjidic/kanjiutils.c.s

src/kanjidic/main.o: src/kanjidic/main.c.o
.PHONY : src/kanjidic/main.o

# target to build an object file
src/kanjidic/main.c.o:
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/main.c.o
.PHONY : src/kanjidic/main.c.o

src/kanjidic/main.i: src/kanjidic/main.c.i
.PHONY : src/kanjidic/main.i

# target to preprocess a source file
src/kanjidic/main.c.i:
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/main.c.i
.PHONY : src/kanjidic/main.c.i

src/kanjidic/main.s: src/kanjidic/main.c.s
.PHONY : src/kanjidic/main.s

# target to generate assembly for a file
src/kanjidic/main.c.s:
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/main.c.s
.PHONY : src/kanjidic/main.c.s

src/kanjidic/preferences.o: src/kanjidic/preferences.c.o
.PHONY : src/kanjidic/preferences.o

# target to build an object file
src/kanjidic/preferences.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/preferences.c.o
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/preferences.c.o
.PHONY : src/kanjidic/preferences.c.o

src/kanjidic/preferences.i: src/kanjidic/preferences.c.i
.PHONY : src/kanjidic/preferences.i

# target to preprocess a source file
src/kanjidic/preferences.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/preferences.c.i
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/preferences.c.i
.PHONY : src/kanjidic/preferences.c.i

src/kanjidic/preferences.s: src/kanjidic/preferences.c.s
.PHONY : src/kanjidic/preferences.s

# target to generate assembly for a file
src/kanjidic/preferences.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/preferences.c.s
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/preferences.c.s
.PHONY : src/kanjidic/preferences.c.s

src/kanjidic/radical_list.o: src/kanjidic/radical_list.c.o
.PHONY : src/kanjidic/radical_list.o

# target to build an object file
src/kanjidic/radical_list.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/radical_list.c.o
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/radical_list.c.o
.PHONY : src/kanjidic/radical_list.c.o

src/kanjidic/radical_list.i: src/kanjidic/radical_list.c.i
.PHONY : src/kanjidic/radical_list.i

# target to preprocess a source file
src/kanjidic/radical_list.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/radical_list.c.i
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/radical_list.c.i
.PHONY : src/kanjidic/radical_list.c.i

src/kanjidic/radical_list.s: src/kanjidic/radical_list.c.s
.PHONY : src/kanjidic/radical_list.s

# target to generate assembly for a file
src/kanjidic/radical_list.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/kanjidic/radical_list.c.s
	$(MAKE) -f CMakeFiles/bin/kanjidic.dir/build.make CMakeFiles/bin/kanjidic.dir/src/kanjidic/radical_list.c.s
.PHONY : src/kanjidic/radical_list.c.s

src/worddic/callbacks.o: src/worddic/callbacks.c.o
.PHONY : src/worddic/callbacks.o

# target to build an object file
src/worddic/callbacks.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/worddic/callbacks.c.o
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/worddic/callbacks.c.o
.PHONY : src/worddic/callbacks.c.o

src/worddic/callbacks.i: src/worddic/callbacks.c.i
.PHONY : src/worddic/callbacks.i

# target to preprocess a source file
src/worddic/callbacks.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/worddic/callbacks.c.i
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/worddic/callbacks.c.i
.PHONY : src/worddic/callbacks.c.i

src/worddic/callbacks.s: src/worddic/callbacks.c.s
.PHONY : src/worddic/callbacks.s

# target to generate assembly for a file
src/worddic/callbacks.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/worddic/callbacks.c.s
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/worddic/callbacks.c.s
.PHONY : src/worddic/callbacks.c.s

src/worddic/inflection.o: src/worddic/inflection.c.o
.PHONY : src/worddic/inflection.o

# target to build an object file
src/worddic/inflection.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/worddic/inflection.c.o
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/worddic/inflection.c.o
.PHONY : src/worddic/inflection.c.o

src/worddic/inflection.i: src/worddic/inflection.c.i
.PHONY : src/worddic/inflection.i

# target to preprocess a source file
src/worddic/inflection.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/worddic/inflection.c.i
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/worddic/inflection.c.i
.PHONY : src/worddic/inflection.c.i

src/worddic/inflection.s: src/worddic/inflection.c.s
.PHONY : src/worddic/inflection.s

# target to generate assembly for a file
src/worddic/inflection.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/worddic/inflection.c.s
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/worddic/inflection.c.s
.PHONY : src/worddic/inflection.c.s

src/worddic/main.o: src/worddic/main.c.o
.PHONY : src/worddic/main.o

# target to build an object file
src/worddic/main.c.o:
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/worddic/main.c.o
.PHONY : src/worddic/main.c.o

src/worddic/main.i: src/worddic/main.c.i
.PHONY : src/worddic/main.i

# target to preprocess a source file
src/worddic/main.c.i:
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/worddic/main.c.i
.PHONY : src/worddic/main.c.i

src/worddic/main.s: src/worddic/main.c.s
.PHONY : src/worddic/main.s

# target to generate assembly for a file
src/worddic/main.c.s:
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/worddic/main.c.s
.PHONY : src/worddic/main.c.s

src/worddic/preferences.o: src/worddic/preferences.c.o
.PHONY : src/worddic/preferences.o

# target to build an object file
src/worddic/preferences.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/worddic/preferences.c.o
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/worddic/preferences.c.o
.PHONY : src/worddic/preferences.c.o

src/worddic/preferences.i: src/worddic/preferences.c.i
.PHONY : src/worddic/preferences.i

# target to preprocess a source file
src/worddic/preferences.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/worddic/preferences.c.i
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/worddic/preferences.c.i
.PHONY : src/worddic/preferences.c.i

src/worddic/preferences.s: src/worddic/preferences.c.s
.PHONY : src/worddic/preferences.s

# target to generate assembly for a file
src/worddic/preferences.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/worddic/preferences.c.s
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/worddic/preferences.c.s
.PHONY : src/worddic/preferences.c.s

src/worddic/worddic.o: src/worddic/worddic.c.o
.PHONY : src/worddic/worddic.o

# target to build an object file
src/worddic/worddic.c.o:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/worddic/worddic.c.o
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/worddic/worddic.c.o
.PHONY : src/worddic/worddic.c.o

src/worddic/worddic.i: src/worddic/worddic.c.i
.PHONY : src/worddic/worddic.i

# target to preprocess a source file
src/worddic/worddic.c.i:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/worddic/worddic.c.i
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/worddic/worddic.c.i
.PHONY : src/worddic/worddic.c.i

src/worddic/worddic.s: src/worddic/worddic.c.s
.PHONY : src/worddic/worddic.s

# target to generate assembly for a file
src/worddic/worddic.c.s:
	$(MAKE) -f CMakeFiles/bin/gjitenkai.dir/build.make CMakeFiles/bin/gjitenkai.dir/src/worddic/worddic.c.s
	$(MAKE) -f CMakeFiles/bin/worddic.dir/build.make CMakeFiles/bin/worddic.dir/src/worddic/worddic.c.s
.PHONY : src/worddic/worddic.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... bin/kanjidic"
	@echo "... list_install_components"
	@echo "... bin/gjitenkai"
	@echo "... bin/worddic"
	@echo "... src/common/callbacks.o"
	@echo "... src/common/callbacks.i"
	@echo "... src/common/callbacks.s"
	@echo "... src/common/conf.o"
	@echo "... src/common/conf.i"
	@echo "... src/common/conf.s"
	@echo "... src/common/dicfile.o"
	@echo "... src/common/dicfile.i"
	@echo "... src/common/dicfile.s"
	@echo "... src/common/dicutil.o"
	@echo "... src/common/dicutil.i"
	@echo "... src/common/dicutil.s"
	@echo "... src/common/error.o"
	@echo "... src/common/error.i"
	@echo "... src/common/error.s"
	@echo "... src/gjitenkai/callbacks.o"
	@echo "... src/gjitenkai/callbacks.i"
	@echo "... src/gjitenkai/callbacks.s"
	@echo "... src/gjitenkai/gjitenkai.o"
	@echo "... src/gjitenkai/gjitenkai.i"
	@echo "... src/gjitenkai/gjitenkai.s"
	@echo "... src/gjitenkai/main.o"
	@echo "... src/gjitenkai/main.i"
	@echo "... src/gjitenkai/main.s"
	@echo "... src/kanjidic/callbacks.o"
	@echo "... src/kanjidic/callbacks.i"
	@echo "... src/kanjidic/callbacks.s"
	@echo "... src/kanjidic/kanji_item.o"
	@echo "... src/kanjidic/kanji_item.i"
	@echo "... src/kanjidic/kanji_item.s"
	@echo "... src/kanjidic/kanjidic.o"
	@echo "... src/kanjidic/kanjidic.i"
	@echo "... src/kanjidic/kanjidic.s"
	@echo "... src/kanjidic/kanjifile.o"
	@echo "... src/kanjidic/kanjifile.i"
	@echo "... src/kanjidic/kanjifile.s"
	@echo "... src/kanjidic/kanjiutils.o"
	@echo "... src/kanjidic/kanjiutils.i"
	@echo "... src/kanjidic/kanjiutils.s"
	@echo "... src/kanjidic/main.o"
	@echo "... src/kanjidic/main.i"
	@echo "... src/kanjidic/main.s"
	@echo "... src/kanjidic/preferences.o"
	@echo "... src/kanjidic/preferences.i"
	@echo "... src/kanjidic/preferences.s"
	@echo "... src/kanjidic/radical_list.o"
	@echo "... src/kanjidic/radical_list.i"
	@echo "... src/kanjidic/radical_list.s"
	@echo "... src/worddic/callbacks.o"
	@echo "... src/worddic/callbacks.i"
	@echo "... src/worddic/callbacks.s"
	@echo "... src/worddic/inflection.o"
	@echo "... src/worddic/inflection.i"
	@echo "... src/worddic/inflection.s"
	@echo "... src/worddic/main.o"
	@echo "... src/worddic/main.i"
	@echo "... src/worddic/main.s"
	@echo "... src/worddic/preferences.o"
	@echo "... src/worddic/preferences.i"
	@echo "... src/worddic/preferences.s"
	@echo "... src/worddic/worddic.o"
	@echo "... src/worddic/worddic.i"
	@echo "... src/worddic/worddic.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

